import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NEXTAUTH_URL: z.string().url().optional(),
    NEXTAUTH_SECRET: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    GITHUB_CLIENT_ID: z.string().min(1),
    GITHUB_CLIENT_SECRET: z.string().min(1),
    DATABASE_URL: z.string().min(1),
    TIER_BASE_URL: z.string().min(1),
    TIER_API_KEY: z.string().min(1),
    TIER_FREE_PLAN_ID: z.string().min(1),
    TIER_STARTUP_PLAN_ID: z.string().min(1),
    TIER_BUSINESS_PLAN_ID: z.string().min(1),
    TIER_BASE_FEATURE_ID: z.string().min(1),
    TIER_AICOPY_FEATURE_ID: z.string().min(1),
    TIER_EXTRACOPY_FEATURE_ID: z.string().min(1),
    OPENAI_API_KEY: z.string().min(1),
    SMTP_FROM: z.string().min(1),
    POSTMARK_API_TOKEN: z.string().min(1),
    POSTMARK_SIGN_IN_TEMPLATE: z.string().min(1),
    POSTMARK_ACTIVATION_TEMPLATE: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().min(1),
  },
  runtimeEnv: {
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
    DATABASE_URL: process.env.DATABASE_URL,
    TIER_BASE_URL: process.env.TIER_BASE_URL,
    TIER_API_KEY: process.env.TIER_API_KEY,
    TIER_FREE_PLAN_ID: process.env.TIER_FREE_PLAN_ID,
    TIER_STARTUP_PLAN_ID: process.env.TIER_STARTUP_PLAN_ID,
    TIER_BUSINESS_PLAN_ID: process.env.TIER_BUSINESS_PLAN_ID,
    TIER_BASE_FEATURE_ID: process.env.TIER_BASE_FEATURE_ID,
    TIER_AICOPY_FEATURE_ID: process.env.TIER_AICOPY_FEATURE_ID,
    TIER_EXTRACOPY_FEATURE_ID: process.env.TIER_EXTRACOPY_FEATURE_ID,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    SMTP_FROM: process.env.SMTP_FROM,
    POSTMARK_API_TOKEN: process.env.POSTMARK_API_TOKEN,
    POSTMARK_SIGN_IN_TEMPLATE: process.env.POSTMARK_SIGN_IN_TEMPLATE,
    POSTMARK_ACTIVATION_TEMPLATE: process.env.POSTMARK_ACTIVATION_TEMPLATE,
  },
});
